/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChatUtility_PeerConnection */

#ifndef _Included_ChatUtility_PeerConnection
#define _Included_ChatUtility_PeerConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChatUtility_PeerConnection
 * Method:    sender
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ChatUtility_PeerConnection_sender
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     ChatUtility_PeerConnection
 * Method:    receiver
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ChatUtility_PeerConnection_receiver
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
